version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email_core_app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - redis
    environment:
      - NODE_ENV=production
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_CALLBACK_URL=${AZURE_CALLBACK_URL}
    # volumes:
    #   - .:/app
    #   - /app/node_modules

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

volumes:
  esdata:
    driver: local
  redisdata:
    driver: local
